# Generated by Django 4.2.1 on 2023-07-28 03:43

import api.model.Chat
import api.model.Member
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('ChatID', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('Wallpaper_Image', models.ImageField(upload_to=api.model.Chat.chat_wallpaper_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('ID', models.CharField(default=api.model.Member.generate_unique_id, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('FirstName', models.CharField(default='bruno', max_length=255)),
                ('LastName', models.CharField(default='mars', max_length=255)),
                ('BirthDate', models.DateField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=255)),
                ('PhoneNumber', models.CharField(default='01012345678', max_length=255)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('PersonalImage', models.ImageField(upload_to=api.model.Member.member_image_path)),
                ('PersonalBio', models.TextField()),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('MsgID', models.AutoField(primary_key=True, serialize=False)),
                ('SendTime', models.DateTimeField(auto_now_add=True)),
                ('MsgBody', models.TextField(blank=True, null=True)),
                ('MsgImage', models.BinaryField(blank=True, null=True)),
                ('ChatID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chat')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='MemOneID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mem1', to='api.member'),
        ),
        migrations.AddField(
            model_name='chat',
            name='MemTwoID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mem2', to='api.member'),
        ),
    ]
