# Generated by Django 4.2.1 on 2024-02-03 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_chat_wallpaper_image_alter_member_personalbio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=500, unique=True)),
                ('token_expiry', models.DateTimeField()),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.member')),
            ],
        ),
    ]
