# Generated by Django 4.2.1 on 2024-02-03 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_membertoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='ID',
            new_name='id',
        ),
    ]
