# Generated by Django 4.2.1 on 2024-02-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_id_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membertoken',
            name='token',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
